export const currencyCountryMap = {
    USD: 'United States (USD)',
    EUR: 'European Union (EUR)',
    GBP: 'United Kingdom (GBP)',
    JPY: 'Japan (JPY)',
    AUD: 'Australia (AUD)',
    CAD: 'Canada (CAD)',
    CHF: 'Switzerland (CHF)',
    CNY: 'China (CNY)',
    NZD: 'New Zealand (NZD)',
    INR: 'India (INR)',
    ZAR: 'South Africa (ZAR)',
    MXN: 'Mexico (MXN)',
    BRL: 'Brazil (BRL)',
    RUB: 'Russia (RUB)',
    KRW: 'South Korea (KRW)',
    SGD: 'Singapore (SGD)',
    NOK: 'Norway (NOK)',
    SEK: 'Sweden (SEK)',
    DKK: 'Denmark (DKK)',
    HKD: 'Hong Kong (HKD)',
    TRY: 'Turkey (TRY)',
    THB: 'Thailand (THB)',
    MYR: 'Malaysia (MYR)',
    IDR: 'Indonesia (IDR)',
    PHP: 'Philippines (PHP)',
    AED: 'United Arab Emirates (AED)',
    AFN: 'Afghanistan (AFN)',
    ALL: 'Albania (ALL)',
    AMD: 'Armenia (AMD)',
    ANG: 'Netherlands Antillean (ANG)',
    AOA: 'Angola (AOA)',
    ARS: 'Argentina (ARS)',
    AWG: 'Aruba (AWG)',
    AZN: 'Azerbaijan (AZN)',
    BAM: 'Bosnia-Herzegovina (BAM)',
    BBD: 'Barbados (BBD)',
    BDT: 'Bangladesh (BDT)',
    BGN: 'Bulgaria (BGN)',
    BHD: 'Bahrain (BHD)',
    BIF: 'Burundi (BIF)',
    BMD: 'Bermuda (BMD)',
    BND: 'Brunei (BND)',
    BOB: 'Bolivia (BOB)',
    BSD: 'Bahamas (BSD)',
    BTN: 'Bhutan (BTN)',
    BWP: 'Botswana (BWP)',
    BYN: 'Belarus (BYN)',
    BZD: 'Belize (BZD)',
    CDF: 'Congo (CDF)',
    CLP: 'Chile (CLP)',
    COP: 'Colombia (COP)',
    CRC: 'Costa Rica (CRC)',
    CUP: 'Cuba (CUP)',
    CVE: 'Cape Verde (CVE)',
    CZK: 'Czech Republic (CZK)',
    DJF: 'Djibouti (DJF)',
    DOP: 'Dominican Republic (DOP)',
    DZD: 'Algeria (DZD)',
    EGP: 'Egypt (EGP)',
    ERN: 'Eritrea (ERN)',
    ETB: 'Ethiopia (ETB)',
    FJD: 'Fiji (FJD)',
    FKP: 'Falkland Islands (FKP)',
    GEL: 'Georgia (GEL)',
    GHS: 'Ghana (GHS)',
    GIP: 'Gibraltar (GIP)',
    GMD: 'Gambia (GMD)',
    GNF: 'Guinea (GNF)',
    GTQ: 'Guatemala (GTQ)',
    GYD: 'Guyana (GYD)',
    HNL: 'Honduras (HNL)',
    HRK: 'Croatia (HRK)',
    HTG: 'Haiti (HTG)',
    HUF: 'Hungary (HUF)',
    ILS: 'Israel (ILS)',
    IQD: 'Iraq (IQD)',
    IRR: 'Iran (IRR)',
    ISK: 'Iceland (ISK)',
    JMD: 'Jamaica (JMD)',
    JOD: 'Jordan (JOD)',
    KES: 'Kenya (KES)',
    KGS: 'Kyrgyzstan (KGS)',
    KHR: 'Cambodia (KHR)',
    KMF: 'Comoros (KMF)',
    KWD: 'Kuwait (KWD)',
    KYD: 'Cayman Islands (KYD)',
    KZT: 'Kazakhstan (KZT)',
    LAK: 'Laos (LAK)',
    LBP: 'Lebanon (LBP)',
    LKR: 'Sri Lanka (LKR)',
    LRD: 'Liberia (LRD)',
    LSL: 'Lesotho (LSL)',
    LYD: 'Libya (LYD)',
    MAD: 'Morocco (MAD)',
    MDL: 'Moldova (MDL)',
    MGA: 'Madagascar (MGA)',
    MKD: 'North Macedonia (MKD)',
    MMK: 'Myanmar (MMK)',
    MNT: 'Mongolia (MNT)',
    MOP: 'Macau (MOP)',
    MRU: 'Mauritania (MRU)',
    MUR: 'Mauritius (MUR)',
    MVR: 'Maldives (MVR)',
    MWK: 'Malawi (MWK)',
    MZN: 'Mozambique (MZN)',
    NAD: 'Namibia (NAD)',
    NGN: 'Nigeria (NGN)',
    NIO: 'Nicaragua (NIO)',
    OMR: 'Oman (OMR)',
    PAB: 'Panama (PAB)',
    PEN: 'Peru (PEN)',
    PGK: 'Papua New Guinea (PGK)',
    PKR: 'Pakistan (PKR)',
    PLN: 'Poland (PLN)',
    PYG: 'Paraguay (PYG)',
    QAR: 'Qatar (QAR)',
    RON: 'Romania (RON)',
    RSD: 'Serbia (RSD)',
    RWF: 'Rwanda (RWF)',
    SAR: 'Saudi Arabia (SAR)',
    SBD: 'Solomon Islands (SBD)',
    SCR: 'Seychelles (SCR)',
    SDG: 'Sudan (SDG)',
    SLE: 'Sierra Leone (SLE)',
    SLL: 'Sierra Leone (SLL)',
    SOS: 'Somalia (SOS)',
    SRD: 'Suriname (SRD)',
    SSP: 'South Sudan (SSP)',
    STN: 'São Tomé and Príncipe (STN)',
    SYP: 'Syria (SYP)',
    SZL: 'Eswatini (SZL)',
    TJS: 'Tajikistan (TJS)',
    TMT: 'Turkmenistan (TMT)',
    TND: 'Tunisia (TND)',
    TOP: 'Tonga (TOP)',
    TTD: 'Trinidad and Tobago (TTD)',
    TVD: 'Tuvalu (TVD)',
    TWD: 'Taiwan (TWD)',
    TZS: 'Tanzania (TZS)',
    UAH: 'Ukraine (UAH)',
    UGX: 'Uganda (UGX)',
    UYU: 'Uruguay (UYU)',
    UZS: 'Uzbekistan (UZS)',
    VES: 'Venezuela (VES)',
    VND: 'Vietnam (VND)',
    VUV: 'Vanuatu (VUV)',
    WST: 'Samoa (WST)',
    XAF: 'Central African CFA (XAF)',
    XCD: 'East Caribbean (XCD)',
    XDR: 'International Monetary Fund (XDR)',
    XOF: 'West African CFA (XOF)',
    XPF: 'CFP Franc (XPF)',
    YER: 'Yemen (YER)',
    ZMW: 'Zambia (ZMW)',
    ZWL: 'Zimbabwe (ZWL)',
  };
  